# Generated by Django 4.2.4 on 2024-09-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_tag_created_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dead_line_time',
            field=models.DateTimeField(null=True),
        ),
    ]
