# Generated by Django 4.2.4 on 2024-09-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_todouser_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='telegram_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
