# Generated by Django 4.2.4 on 2024-09-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_todouser_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todouser',
            name='telegram_id',
        ),
    ]
