# Generated by Django 4.2.4 on 2024-09-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_todouser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='id',
            field=models.CharField(blank=True, max_length=64, primary_key=True, serialize=False),
        ),
    ]
